{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import re\n",
    "import ast\n",
    "import time\n",
    "import requests\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import os.path\n",
    "import urllib.request\n",
    "import concurrent.futures\n",
    "from os import listdir\n",
    "from stem import Signal\n",
    "from requests import get\n",
    "from bs4 import BeautifulSoup\n",
    "from datetime import datetime\n",
    "from os.path import isfile, join\n",
    "from stem.control import Controller\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>tconst</th>\n",
       "      <th>stars</th>\n",
       "      <th>oscarWins</th>\n",
       "      <th>nominations</th>\n",
       "      <th>wins</th>\n",
       "      <th>releaseDate</th>\n",
       "      <th>releaseCountry</th>\n",
       "      <th>plotKeywords</th>\n",
       "      <th>budget</th>\n",
       "      <th>worldwideGross</th>\n",
       "      <th>metascore</th>\n",
       "      <th>musicProducer</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>tt0014799</td>\n",
       "      <td>[nm0265550, nm0370407, nm0550195]</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1924-05-31</td>\n",
       "      <td>UK</td>\n",
       "      <td>[]</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>tt0014843</td>\n",
       "      <td>[nm0427659, nm0107574, nm0421138]</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1924-08-24</td>\n",
       "      <td>USA</td>\n",
       "      <td>[]</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>tt0014809</td>\n",
       "      <td>[nm0267916, nm0119572, nm0055809]</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1924-04-08</td>\n",
       "      <td>USA</td>\n",
       "      <td>[]</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>tt0014751</td>\n",
       "      <td>[nm0403710, nm0744408]</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>[]</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>tt0014812</td>\n",
       "      <td>[nm0556953, nm0531962, nm0645941]</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1924-12-28</td>\n",
       "      <td>USA</td>\n",
       "      <td>[]</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "      tconst                              stars  oscarWins  nominations  wins  \\\n",
       "0  tt0014799  [nm0265550, nm0370407, nm0550195]          0            0     0   \n",
       "1  tt0014843  [nm0427659, nm0107574, nm0421138]          0            0     0   \n",
       "2  tt0014809  [nm0267916, nm0119572, nm0055809]          0            0     0   \n",
       "3  tt0014751             [nm0403710, nm0744408]          0            0     0   \n",
       "4  tt0014812  [nm0556953, nm0531962, nm0645941]          0            0     0   \n",
       "\n",
       "  releaseDate releaseCountry plotKeywords budget worldwideGross metascore  \\\n",
       "0  1924-05-31             UK           []   None           None      None   \n",
       "1  1924-08-24            USA           []   None           None      None   \n",
       "2  1924-04-08            USA           []   None           None      None   \n",
       "3        None           None           []   None           None      None   \n",
       "4  1924-12-28            USA           []   None           None      None   \n",
       "\n",
       "  musicProducer  \n",
       "0          None  \n",
       "1          None  \n",
       "2          None  \n",
       "3          None  \n",
       "4          None  "
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "movie_subset = pd.read_pickle(\"./pickles/complete_178118.pkl\")\n",
    "movie_subset.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>tconst</th>\n",
       "      <th>stars</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>tt0014799</td>\n",
       "      <td>nm0265550</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>tt0014799</td>\n",
       "      <td>nm0370407</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>tt0014799</td>\n",
       "      <td>nm0550195</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>tt0014843</td>\n",
       "      <td>nm0427659</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>tt0014843</td>\n",
       "      <td>nm0107574</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "      tconst      stars\n",
       "0  tt0014799  nm0265550\n",
       "0  tt0014799  nm0370407\n",
       "0  tt0014799  nm0550195\n",
       "1  tt0014843  nm0427659\n",
       "1  tt0014843  nm0107574"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "stars_exploded = movie_subset.explode('stars')[['tconst', 'stars']]\n",
    "stars_exploded.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "138245"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "stars_exploded.stars.nunique()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "stars_counts = stars_exploded\\\n",
    "                    .groupby('stars')\\\n",
    "                    .count()\\\n",
    "                    .rename(columns={\"tconst\": \"count\"})\\\n",
    "                    .sort_values(['count'], ascending=False)\n",
    "stars_counts.index.name = 'nconst'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>count</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>nconst</th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>nm0323379</th>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>nm0098627</th>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>nm0073596</th>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>nm1054406</th>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>nm1030940</th>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>nm0670816</th>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>nm0163019</th>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>nm0670779</th>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>nm0670771</th>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>nm9989884</th>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>87400 rows × 1 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "           count\n",
       "nconst          \n",
       "nm0323379      2\n",
       "nm0098627      2\n",
       "nm0073596      2\n",
       "nm1054406      1\n",
       "nm1030940      1\n",
       "...          ...\n",
       "nm0670816      1\n",
       "nm0163019      1\n",
       "nm0670779      1\n",
       "nm0670771      1\n",
       "nm9989884      1\n",
       "\n",
       "[87400 rows x 1 columns]"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "stars_counts.tail(87400) "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Close to 90000 stars have starred in only 1 movie in the chosen movie subset. For the purpose of bringing down the actors count for scraping,  for the moment, let's consider only the actors that have starred in more than 1 movie in the chosen movie subset. \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Jessica Alba: 4 movies\n",
      "Billy Boyd (Pippin from LOTR): 1 movies\n",
      "Will Smith: 12 movies\n",
      "Morgan Freeman: 26 movies\n"
     ]
    }
   ],
   "source": [
    "print(\"Jessica Alba: {0} movies\".format(stars_counts.loc['nm0004695']['count']))\n",
    "print(\"Billy Boyd (Pippin from LOTR): {0} movies\".format(stars_counts.loc['nm0101710']['count']))\n",
    "print(\"Will Smith: {0} movies\".format(stars_counts.loc['nm0000226']['count']))\n",
    "print(\"Morgan Freeman: {0} movies\".format(stars_counts.loc['nm0000151']['count']))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "50848"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "stars_subset = stars_counts[stars_counts['count'] > 1]\n",
    "len(stars_subset)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Scraping"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_tor_session(prev_session):\n",
    "    session = requests.session()\n",
    "    # Tor uses the 9050 port as the default socks port\n",
    "    session.proxies = {'http':  'socks5://127.0.0.1:9050',\n",
    "                       'https': 'socks5://127.0.0.1:9050'}\n",
    "    return session\n",
    "\n",
    "def renew_connection():\n",
    "    with Controller.from_port(port = 9051) as controller:\n",
    "        controller.authenticate(password=\"password\")\n",
    "\n",
    "def get_data(session, url):\n",
    "    nconst=url.rsplit('/', 2)[-2]\n",
    "    result = {\n",
    "        'nconst': nconst,\n",
    "        'year': None,\n",
    "        'category': None,\n",
    "        'w_n': None,\n",
    "        'description': None,\n",
    "        'movie': None,\n",
    "        'tconst': None \n",
    "    }\n",
    "    \n",
    "    with session.get(url) as req:\n",
    "        req.raise_for_status()    \n",
    "    \n",
    "        body=req.text\n",
    "\n",
    "        soup=BeautifulSoup(body,'html.parser')\n",
    "        awards=soup.find_all('tr')\n",
    "        if awards is not None:\n",
    "            for award in awards:\n",
    "                if award.find('td', class_='award_year') is not None:\n",
    "                    if award.find('td', class_='award_year').find('a') is not None:\n",
    "                        year = award.find('td', class_='award_year').find('a').text\n",
    "                        if year is not None:\n",
    "                            try:\n",
    "                                year = int(year.replace(\"\\n\", \"\").strip())\n",
    "                                result['year'] = year\n",
    "                            except:\n",
    "                                print(\"Failed to parse int year {0}\".format(year))\n",
    "\n",
    "\n",
    "\n",
    "                if award.find('span',class_='award_category') is not None:\n",
    "                    result['category'] = award.find('span',class_='award_category').text\n",
    "\n",
    "                if award.find('td',class_=\"award_outcome\") is not None:\n",
    "                    outcome = award.find('td',class_=\"award_outcome\").find('b')\n",
    "                    if outcome is not None:\n",
    "                        outcome_txt = outcome.text\n",
    "                        if outcome_txt is not None:\n",
    "                            result['w_n'] = outcome_txt.replace(\"\\n\", \"\").strip()\n",
    "\n",
    "                if award.find('td', class_='award_description') is not None:\n",
    "                    award_txt = award.find('td',class_='award_description').find(text=True, recursive=False)\n",
    "                    award_info = award.find('td',class_='award_description').find('a')\n",
    "                    if award_txt is not None:\n",
    "                        result['description'] = award_txt.replace(\"\\n\", \"\").strip()\n",
    "\n",
    "                    if award_info is not None:\n",
    "                        result['movie'] = award_info.text\n",
    "                        tconst_res = re.search('tt\\d{7}', award_info.get('href'))\n",
    "                        if tconst_res is not None:\n",
    "                            result['tconst'] = tconst_res.group(0)\n",
    "\n",
    "            return result"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "https://www.imdb.com/name/nm0249982/awards generated an exception: [('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]. Added to retry list.\n",
      "https://www.imdb.com/name/nm0823633/awards generated an exception: [('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]. Added to retry list.\n",
      "https://www.imdb.com/name/nm0453520/awards generated an exception: [('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]. Added to retry list.\n",
      "https://www.imdb.com/name/nm0004437/awards generated an exception: [('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]. Added to retry list.\n",
      "https://www.imdb.com/name/nm0369058/awards generated an exception: [('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]. Added to retry list.\n",
      "https://www.imdb.com/name/nm0004462/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0004462/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1202c6b38>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0000053/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0000053/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x12029fd68>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0000367/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0000367/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f40be10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0201638/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0201638/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x12146e668>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0000818/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0000818/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11a9c1fd0>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0800302/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0800302/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1202ae0b8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0849011/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0849011/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x12029f9b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0874781/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0874781/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f52f9e8>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0674741/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0674741/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f52fbe0>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0221488/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0221488/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f549128>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0214150/awards generated an exception: [('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]. Added to retry list.\n",
      "https://www.imdb.com/name/nm0316995/awards generated an exception: [('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]. Added to retry list.\n",
      "https://www.imdb.com/name/nm0001120/awards generated an exception: [('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]. Added to retry list.\n",
      "https://www.imdb.com/name/nm0712660/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0712660/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f549940>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0802374/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0802374/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f549860>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0000051/awards generated an exception: [('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]. Added to retry list.\n",
      "https://www.imdb.com/name/nm1066548/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm1066548/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f549cc0>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0101071/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0101071/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x12146e8d0>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0254381/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0254381/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f556198>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0004334/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0004334/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f5566d8>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0001766/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0001766/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f556908>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0001076/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0001076/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f5491d0>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0626259/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0626259/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f56d1d0>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0721073/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0721073/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f56d080>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0320760/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0320760/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f56d438>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0084435/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0084435/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f56d0f0>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0785664/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0785664/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f56dcf8>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0419685/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0419685/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f5567f0>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0018437/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0018437/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f56dba8>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0534045/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0534045/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f56dda0>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0869451/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0869451/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f5862e8>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0764762/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0764762/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f56d668>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0122470/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0122470/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f586908>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0729473/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0729473/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1202bd080>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0000012/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0000012/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1202c6a20>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0000802/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0000802/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f586ac8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0148974/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0148974/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f599668>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0015000/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0015000/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f586b38>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0701633/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0701633/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f599438>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0853604/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0853604/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f5992b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0107574/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0107574/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f599518>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0799108/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0799108/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f5991d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0185568/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0185568/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f5b6940>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0358076/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0358076/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f5b6470>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0000472/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0000472/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f5b6898>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0002154/awards generated an exception: [('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]. Added to retry list.\n",
      "https://www.imdb.com/name/nm0406737/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0406737/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f5b6fd0>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0272794/awards generated an exception: [('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]. Added to retry list.\n",
      "https://www.imdb.com/name/nm0001935/awards generated an exception: [('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]. Added to retry list.\n",
      "https://www.imdb.com/name/nm0113902/awards generated an exception: [('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]. Added to retry list.\n",
      "https://www.imdb.com/name/nm0295992/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0295992/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f5b62e8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0107575/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0107575/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f5c9f98>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0363218/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0363218/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f5ed710>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0529876/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0529876/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f5db668>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0006763/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0006763/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f5db400>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0098376/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0098376/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f5dbcc0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0199087/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0199087/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f5c9a58>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0556953/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0556953/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f5db9e8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0812929/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0812929/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f5fab00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0001229/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0001229/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f5fa8d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0207023/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0207023/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f5faba8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0000784/awards generated an exception: [('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]. Added to retry list.\n",
      "https://www.imdb.com/name/nm0035159/awards generated an exception: [('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]. Added to retry list.\n",
      "https://www.imdb.com/name/nm0367928/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0367928/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f60efd0>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0288003/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0288003/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f61d0f0>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0893449/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0893449/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f5dbf98>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0000897/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0000897/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f60ef28>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0000440/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0000440/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f62b080>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0603875/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0603875/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f61db38>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0001870/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0001870/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f61d828>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0301556/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0301556/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f6393c8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0089524/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0089524/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f5fa860>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0848910/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0848910/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f5db240>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0000313/awards generated an exception: [('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]. Added to retry list.\n",
      "https://www.imdb.com/name/nm0007042/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0007042/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x123142390>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0373535/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0373535/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1234ebc88>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0085038/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0085038/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x12682a9b0>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0113873/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0113873/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x120838cf8>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0000072/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0000072/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x123492320>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0299885/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0299885/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x12331ebe0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0156484/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0156484/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1234c2908>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0002011/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0002011/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11aafcb70>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0350324/awards generated an exception: [('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]. Added to retry list.\n",
      "https://www.imdb.com/name/nm0000164/awards generated an exception: [('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]. Added to retry list.\n",
      "https://www.imdb.com/name/nm0052333/awards generated an exception: [('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]. Added to retry list.\n",
      "https://www.imdb.com/name/nm0624470/awards generated an exception: [('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]. Added to retry list.\n",
      "https://www.imdb.com/name/nm0016290/awards generated an exception: [('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]. Added to retry list.\n",
      "https://www.imdb.com/name/nm0401368/awards generated an exception: [('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]. Added to retry list.\n",
      "https://www.imdb.com/name/nm0155546/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0155546/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1234137f0>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0394472/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0394472/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x124fc4320>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0260020/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0260020/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1234c2630>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0475610/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0475610/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x124fc4b70>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0245304/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0245304/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x124fc44e0>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0560962/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0560962/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x121261cc0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0520595/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0520595/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1212616a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm1135609/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm1135609/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x122df6ac8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0259816/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0259816/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x123413240>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0062428/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0062428/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x121261940>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0001805/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0001805/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x120365550>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0619798/awards generated an exception: [('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]. Added to retry list.\n",
      "https://www.imdb.com/name/nm0562920/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0562920/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x120f81ba8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0354878/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0354878/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f66ce80>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0363104/awards generated an exception: [('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]. Added to retry list.\n",
      "https://www.imdb.com/name/nm0014351/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0014351/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x125d3eb70>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0850236/awards generated an exception: [('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]. Added to retry list.\n",
      "https://www.imdb.com/name/nm0016754/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0016754/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x11f66c860>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0015081/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0015081/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1299f8978>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0226158/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0226158/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x125d3ea20>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0275428/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0275428/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1299f8630>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0792911/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0792911/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1205b61d0>: Failed to establish a new connection: [Errno 24] Too many open files',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0015293/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0015293/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1299f8438>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0001336/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0001336/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1299f8be0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0300623/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0300623/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1205b6da0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0034301/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0034301/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1205b6dd8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0473314/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0473314/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1299f8b38>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0002013/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0002013/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1205b6470>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0000086/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0000086/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x12647de10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0002001/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0002001/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x12647dc88>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0000197/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0000197/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x12647de48>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0904303/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0904303/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1274d4a90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n",
      "https://www.imdb.com/name/nm0708048/awards generated an exception: SOCKSHTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /name/nm0708048/awards (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x125d3ef98>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)). Added to retry list.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-c91b4a8ee5a8>\", line 53, in <module>\n",
      "    for future in concurrent.futures.as_completed(future_to_url):\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/concurrent/futures/_base.py\", line 240, in as_completed\n",
      "    waiter.event.wait(wait_timeout)\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/threading.py\", line 551, in wait\n",
      "    signaled = self._cond.wait(timeout)\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/threading.py\", line 295, in wait\n",
      "    waiter.acquire()\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3326, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-10-c91b4a8ee5a8>\", line 87, in <module>\n",
      "    print('''Note: Next, run the script that combine all pickles''')\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/concurrent/futures/_base.py\", line 611, in __exit__\n",
      "    self.shutdown(wait=True)\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/concurrent/futures/thread.py\", line 152, in shutdown\n",
      "    t.join()\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/threading.py\", line 1056, in join\n",
      "    self._wait_for_tstate_lock()\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/threading.py\", line 1072, in _wait_for_tstate_lock\n",
      "    elif lock.acquire(block, timeout):\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2040, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 319, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 353, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/inspect.py\", line 1452, in getframeinfo\n",
      "    lines, lnum = findsource(frame)\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 185, in findsource\n",
      "    lines = linecache.getlines(file, globals_dict)\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/linecache.py\", line 47, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/linecache.py\", line 137, in updatecache\n",
      "    lines = fp.readlines()\n",
      "KeyboardInterrupt\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-c91b4a8ee5a8>\", line 53, in <module>\n",
      "    for future in concurrent.futures.as_completed(future_to_url):\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/concurrent/futures/_base.py\", line 240, in as_completed\n",
      "    waiter.event.wait(wait_timeout)\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/threading.py\", line 551, in wait\n",
      "    signaled = self._cond.wait(timeout)\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/threading.py\", line 295, in wait\n",
      "    waiter.acquire()\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3326, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-10-c91b4a8ee5a8>\", line 87, in <module>\n",
      "    print('''Note: Next, run the script that combine all pickles''')\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/concurrent/futures/_base.py\", line 611, in __exit__\n",
      "    self.shutdown(wait=True)\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/concurrent/futures/thread.py\", line 152, in shutdown\n",
      "    t.join()\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/threading.py\", line 1056, in join\n",
      "    self._wait_for_tstate_lock()\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/threading.py\", line 1072, in _wait_for_tstate_lock\n",
      "    elif lock.acquire(block, timeout):\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2040, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3249, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3343, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2043, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1385, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1288, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1150, in structured_traceback\n",
      "    formatted_exceptions += self.prepare_chained_exception_message(evalue.__cause__)\n",
      "TypeError: must be str, not list\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2040, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 319, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 353, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/inspect.py\", line 1448, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/inspect.py\", line 739, in getmodule\n",
      "    f = getabsfile(module)\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/inspect.py\", line 708, in getabsfile\n",
      "    _filename = getsourcefile(object) or getfile(object)\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/inspect.py\", line 693, in getsourcefile\n",
      "    if os.path.exists(filename):\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/genericpath.py\", line 19, in exists\n",
      "    os.stat(path)\n",
      "KeyboardInterrupt\n"
     ]
    },
    {
     "ename": "TypeError",
     "evalue": "must be str, not list",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-10-c91b4a8ee5a8>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m     52\u001b[0m             \u001b[0mfuture_to_url\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m{\u001b[0m\u001b[0mexecutor\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msubmit\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mget_data\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0msession\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0murl\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0murl\u001b[0m \u001b[0;32mfor\u001b[0m \u001b[0murl\u001b[0m \u001b[0;32min\u001b[0m \u001b[0murl_chunk\u001b[0m\u001b[0;34m}\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 53\u001b[0;31m             \u001b[0;32mfor\u001b[0m \u001b[0mfuture\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mconcurrent\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfutures\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mas_completed\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfuture_to_url\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     54\u001b[0m                 \u001b[0murl\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mfuture_to_url\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mfuture\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.6/concurrent/futures/_base.py\u001b[0m in \u001b[0;36mas_completed\u001b[0;34m(fs, timeout)\u001b[0m\n\u001b[1;32m    239\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 240\u001b[0;31m             \u001b[0mwaiter\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mevent\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwait\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mwait_timeout\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    241\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.6/threading.py\u001b[0m in \u001b[0;36mwait\u001b[0;34m(self, timeout)\u001b[0m\n\u001b[1;32m    550\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0msignaled\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 551\u001b[0;31m                 \u001b[0msignaled\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_cond\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwait\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtimeout\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    552\u001b[0m             \u001b[0;32mreturn\u001b[0m \u001b[0msignaled\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.6/threading.py\u001b[0m in \u001b[0;36mwait\u001b[0;34m(self, timeout)\u001b[0m\n\u001b[1;32m    294\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mtimeout\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 295\u001b[0;31m                 \u001b[0mwaiter\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0macquire\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    296\u001b[0m                 \u001b[0mgotit\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mTrue\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m: ",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;32m~/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py\u001b[0m in \u001b[0;36mshowtraceback\u001b[0;34m(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)\u001b[0m\n\u001b[1;32m   2039\u001b[0m                         \u001b[0;31m# in the engines. This should return a list of strings.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 2040\u001b[0;31m                         \u001b[0mstb\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mvalue\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_render_traceback_\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   2041\u001b[0m                     \u001b[0;32mexcept\u001b[0m \u001b[0mException\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mAttributeError\u001b[0m: 'KeyboardInterrupt' object has no attribute '_render_traceback_'",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m~/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py\u001b[0m in \u001b[0;36mrun_code\u001b[0;34m(self, code_obj, result, async_)\u001b[0m\n\u001b[1;32m   3341\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mresult\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   3342\u001b[0m                 \u001b[0mresult\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0merror_in_exec\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0msys\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mexc_info\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 3343\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mshowtraceback\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mrunning_compiled_code\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   3344\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   3345\u001b[0m             \u001b[0moutflag\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mFalse\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py\u001b[0m in \u001b[0;36mshowtraceback\u001b[0;34m(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)\u001b[0m\n\u001b[1;32m   2041\u001b[0m                     \u001b[0;32mexcept\u001b[0m \u001b[0mException\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   2042\u001b[0m                         stb = self.InteractiveTB.structured_traceback(etype,\n\u001b[0;32m-> 2043\u001b[0;31m                                             value, tb, tb_offset=tb_offset)\n\u001b[0m\u001b[1;32m   2044\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   2045\u001b[0m                     \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_showtraceback\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0metype\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mvalue\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mstb\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.6/site-packages/IPython/core/ultratb.py\u001b[0m in \u001b[0;36mstructured_traceback\u001b[0;34m(self, etype, value, tb, tb_offset, number_of_lines_of_context)\u001b[0m\n\u001b[1;32m   1383\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtb\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtb\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1384\u001b[0m         return FormattedTB.structured_traceback(\n\u001b[0;32m-> 1385\u001b[0;31m             self, etype, value, tb, tb_offset, number_of_lines_of_context)\n\u001b[0m\u001b[1;32m   1386\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1387\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.6/site-packages/IPython/core/ultratb.py\u001b[0m in \u001b[0;36mstructured_traceback\u001b[0;34m(self, etype, value, tb, tb_offset, number_of_lines_of_context)\u001b[0m\n\u001b[1;32m   1286\u001b[0m             \u001b[0;31m# Verbose modes need a full traceback\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1287\u001b[0m             return VerboseTB.structured_traceback(\n\u001b[0;32m-> 1288\u001b[0;31m                 \u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0metype\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mvalue\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtb\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtb_offset\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mnumber_of_lines_of_context\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1289\u001b[0m             )\n\u001b[1;32m   1290\u001b[0m         \u001b[0;32melif\u001b[0m \u001b[0mmode\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;34m'Minimal'\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.6/site-packages/IPython/core/ultratb.py\u001b[0m in \u001b[0;36mstructured_traceback\u001b[0;34m(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)\u001b[0m\n\u001b[1;32m   1148\u001b[0m         \u001b[0mexception\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget_parts_of_chained_exception\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mevalue\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1149\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mexception\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1150\u001b[0;31m             \u001b[0mformatted_exceptions\u001b[0m \u001b[0;34m+=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mprepare_chained_exception_message\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mevalue\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__cause__\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1151\u001b[0m             \u001b[0metype\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mevalue\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0metb\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mexception\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1152\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mTypeError\u001b[0m: must be str, not list"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 265, in _put_conn\n",
      "    self.pool.put(conn, block=False)\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/queue.py\", line 130, in put\n",
      "    raise Full\n",
      "queue.Full\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 97, in _event_pipe\n",
      "    event_pipe = self._local.event_pipe\n",
      "AttributeError: '_thread._local' object has no attribute 'event_pipe'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/logging/__init__.py\", line 996, in emit\n",
      "    stream.write(msg)\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 402, in write\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 205, in schedule\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/ipykernel/iostream.py\", line 101, in _event_pipe\n",
      "    event_pipe = ctx.socket(zmq.PUSH)\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/zmq/sugar/context.py\", line 204, in socket\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/zmq/sugar/socket.py\", line 59, in __init__\n",
      "  File \"zmq/backend/cython/socket.pyx\", line 328, in zmq.backend.cython.socket.Socket.__init__\n",
      "zmq.error.ZMQError: Too many open files\n",
      "Call stack:\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/threading.py\", line 884, in _bootstrap\n",
      "    self._bootstrap_inner()\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/concurrent/futures/thread.py\", line 69, in _worker\n",
      "    work_item.run()\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/concurrent/futures/thread.py\", line 56, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"<ipython-input-9-cefb850489b1>\", line 24, in get_data\n",
      "    with session.get(url) as req:\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/requests/sessions.py\", line 546, in get\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/requests/sessions.py\", line 533, in request\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/requests/sessions.py\", line 686, in send\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/requests/models.py\", line 828, in content\n",
      "    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/requests/models.py\", line 750, in generate\n",
      "    for chunk in self.raw.stream(chunk_size, decode_content=True):\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/urllib3/response.py\", line 490, in stream\n",
      "    for line in self.read_chunked(amt, decode_content=decode_content):\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/urllib3/response.py\", line 694, in read_chunked\n",
      "    self._original_response.close()\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/contextlib.py\", line 88, in __exit__\n",
      "    next(self.gen)\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/urllib3/response.py\", line 402, in _error_catcher\n",
      "    self.release_conn()\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/urllib3/response.py\", line 228, in release_conn\n",
      "  File \"/Users/ruchiranga/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 274, in _put_conn\n",
      "    self.host)\n",
      "Message: 'Connection pool is full, discarding connection: %s'\n",
      "Arguments: ('www.imdb.com',)\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com--- Logging error ---\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n",
      "WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.imdb.com\n"
     ]
    }
   ],
   "source": [
    "# Set the start index and end index. Ip is renewed after each chunk of urls of 'step_size'. \n",
    "# After every chunk, result is written to a pickle. So if you need to stop the execution in the middle, note the\n",
    "# index range of the last successfully written pickle file (from the printed logs) and use the remaining range\n",
    "# for start and end index to resume from where you stopped.\n",
    "postfix = 'actors_subset'\n",
    "s_idx = 0\n",
    "e_idx = len(stars_subset)\n",
    "step_size = 5000\n",
    "pickles_save_dir = './pickles/{0}'.format(postfix)\n",
    "\n",
    "base_url = 'https://www.imdb.com/name/{0}/awards'\n",
    "urls=[]\n",
    "for nconst in stars_subset.index[s_idx:e_idx]:\n",
    "    urls.append(base_url.format(nconst))\n",
    "\n",
    "used_ips = []\n",
    "failed_urls = []\n",
    "\n",
    "with concurrent.futures.ThreadPoolExecutor(max_workers=150) as executor:\n",
    "#     session = get_tor_session(None)\n",
    "    chunk_indeces = np.arange(0, len(urls), step_size)\n",
    "    \n",
    "    for idx, start in enumerate(chunk_indeces, start=1):\n",
    "        start_t = time.time()\n",
    "        finals = []\n",
    "        renew_connection()\n",
    "        \n",
    "        new_ip = ''\n",
    "        with requests.session() as session:\n",
    "        # Tor uses the 9050 port as the default socks port\n",
    "            session.proxies = {'http':  'socks5://127.0.0.1:9050',\n",
    "                               'https': 'socks5://127.0.0.1:9050'}\n",
    "#             session = get_tor_session(session)\n",
    "            new_ip = ast.literal_eval(session.get(\"http://httpbin.org/ip\").text)[\"origin\"].split(\",\")[0]\n",
    "        while new_ip in used_ips:\n",
    "            print(\"Renewed IP {0} already used. Waiting 5s to renew...\".format(new_ip))\n",
    "            time.sleep(5)\n",
    "            renew_connection()\n",
    "            with requests.session() as session:\n",
    "                session.proxies = {'http':  'socks5://127.0.0.1:9050',\n",
    "                                   'https': 'socks5://127.0.0.1:9050'}\n",
    "#             session = get_tor_session(session)\n",
    "                new_ip = ast.literal_eval(session.get(\"http://httpbin.org/ip\").text)[\"origin\"].split(\",\")[0]\n",
    "        used_ips.append(new_ip)\n",
    "\n",
    "        url_chunk = urls[start:start + step_size] + failed_urls\n",
    "        failed_urls = []\n",
    "\n",
    "        with requests.session() as session:\n",
    "            session.proxies = {'http':  'socks5://127.0.0.1:9050',\n",
    "                                   'https': 'socks5://127.0.0.1:9050'}\n",
    "            future_to_url = {executor.submit(get_data, session, url): url for url in url_chunk}\n",
    "            for future in concurrent.futures.as_completed(future_to_url):\n",
    "                url = future_to_url[future]\n",
    "                try:\n",
    "                    data = future.result()\n",
    "                    finals.append(data)\n",
    "                except Exception as exc:\n",
    "                    failed_urls.append(url.strip(\"'\"))\n",
    "                    print('%s generated an exception: %s. Added to retry list.' % (url, exc))\n",
    "\n",
    "            concurrent.futures.wait(\n",
    "                list(future_to_url.keys()), \n",
    "                timeout=None, \n",
    "                return_when=concurrent.futures.ALL_COMPLETED)\n",
    "            end_t = time.time()\n",
    "            print(\"chunk {0} of {1} completed with IP {2}. Took {3} seconds.\"\\\n",
    "                  .format(idx, len(chunk_indeces), new_ip, end_t - start_t))   \n",
    "            actors_df = pd.DataFrame(data=finals)\n",
    "            if not os.path.exists(pickles_save_dir):\n",
    "                os.makedirs(pickles_save_dir)\n",
    "            pickle_path = \"{4}/{0}_{1}-{2}_{3}.pkl\"\\\n",
    "                            .format(idx, start, start + step_size, postfix, pickles_save_dir)\n",
    "            actors_df.to_pickle(pickle_path)\n",
    "            print(\"Wrote pickle {0} with {1} rows\".format(pickle_path, len(actors_df)))\n",
    "        \n",
    "    if len(failed_urls) > 0:\n",
    "        print('\\n\\n\\n\\n!!!**********************************!!!')\n",
    "        print('Failed to retrieve the following URLs.\\n')\n",
    "        print(failed_urls)\n",
    "        print('\\n!!!**********************************!!!')\n",
    "        print('Note: Run the following cell to retry the failed urls')\n",
    "    else:\n",
    "        print(\"\\n\\n\\n\\n!!!**********************************!!!\\n\")\n",
    "        print(\"Scraping succeeded!\")\n",
    "        print('\\n!!!**********************************!!!')\n",
    "        print('''Note: Next, run the script that combine all pickles''')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "'''\n",
    "Run the following script only if there were any failed URLS at the end of the previous script execution.\n",
    "Run this several times if you still see failures until there are none. But if some dont succeed even \n",
    "after multiple attempts, its probably a problem on imdb side and we can just ignore them.\n",
    "'''\n",
    "# urls = failed_urls\n",
    "\n",
    "# if len(urls) > 0:\n",
    "#     retry_failed_urls = []\n",
    "\n",
    "#     with concurrent.futures.ThreadPoolExecutor(max_workers=150) as executor:\n",
    "#         session = get_tor_session(None)\n",
    "#         chunk_indeces = np.arange(0, len(urls), step_size)\n",
    "\n",
    "#         for idx, start in enumerate(chunk_indeces, start=1):\n",
    "#             start_t = time.time()\n",
    "#             finals = []\n",
    "#             renew_connection()\n",
    "#             session = get_tor_session(session)\n",
    "#             new_ip = ast.literal_eval(session.get(\"http://httpbin.org/ip\").text)[\"origin\"].split(\",\")[0]\n",
    "#             while new_ip in used_ips:\n",
    "#                 print(\"Renewed IP {0} already used. Waiting 5s to renew...\".format(new_ip))\n",
    "#                 time.sleep(5)\n",
    "#                 renew_connection()\n",
    "#                 session = get_tor_session(session)\n",
    "#                 new_ip = ast.literal_eval(session.get(\"http://httpbin.org/ip\").text)[\"origin\"].split(\",\")[0]\n",
    "#             used_ips.append(new_ip)\n",
    "\n",
    "#             url_chunk = urls[start:start + step_size] + retry_failed_urls\n",
    "#             retry_failed_urls = []\n",
    "\n",
    "#             future_to_url = {executor.submit(get_data, session, url): url for url in url_chunk}\n",
    "#             for future in concurrent.futures.as_completed(future_to_url):\n",
    "#                 url = future_to_url[future]\n",
    "#                 try:\n",
    "#                     data = future.result()\n",
    "#                     finals.append(data)\n",
    "#                 except Exception as exc:\n",
    "#                     retry_failed_urls.append(url.strip(\"'\"))\n",
    "#                     print('%s generated an exception: %s. Added to retry list.' % (url, exc))\n",
    "\n",
    "#             concurrent.futures.wait(list(future_to_url.keys()), timeout=None, return_when=concurrent.futures.ALL_COMPLETED)\n",
    "#             end_t = time.time()\n",
    "#             print(\"chunk {0} of {1} completed with IP {2}. Took {3} seconds.\".format(idx, len(chunk_indeces), new_ip, end_t - start_t))   \n",
    "#             actors_df = pd.DataFrame(data=finals)\n",
    "#             if len(actors_df) > 0:\n",
    "#                 pickle_path = \"./pickles/actortor/{0}_{1}-{2}_{3}_retry.pkl\".format(idx, start, start + step_size, postfix)\n",
    "#                 actors_df.to_pickle(pickle_path)\n",
    "#                 print(\"Wrote pickle {0} with {1} rows\".format(pickle_path, len(actors_df)))\n",
    "\n",
    "#         if len(retry_failed_urls) > 0:\n",
    "#             print('\\n\\n\\n\\n!!!**********************************!!!')\n",
    "#             print('Retry failed with the following URLs.\\n')\n",
    "#             print(retry_failed_urls)\n",
    "#             print('\\n!!!**********************************!!!')\n",
    "#             print('Note: Run this script several times to see if all succeed.',\n",
    "#             'If some dont, it probably means they wont ever. so just give them up.')\n",
    "#         else:\n",
    "#             print(\"\\n\\n\\n\\n!!!**********************************!!!\\n\")\n",
    "#             print(\"Retry succeeded!\")\n",
    "#             print('\\n!!!**********************************!!!')\n",
    "#             print('''Note: Run the following script to combine all pickles''')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Combine the created pickles into one Dataframe\n",
    "# Ignore any sytem files starting with . or folders if any\n",
    "pickles = [f for f in listdir(pickles_save_dir) if isfile(join(dir_path, f)) and not f.startswith('.')]\n",
    "\n",
    "dfs = list(map(lambda x: pd.read_pickle(\"{0}/{1}\".format(dir_path,x)), pickles))\n",
    "combined_df = pd.concat(dfs)\n",
    "combined_df.reset_index(drop=True, inplace=True)\n",
    "if not os.path.exists('./pickles'):\n",
    "    os.makedirs('./pickles')\n",
    "combined_df.to_pickle(\"./pickles/complete_{1}_{0}.pkl\".format(e_idx, postfix))\n",
    "len(combined_df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
